# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:2.7-stretch

pipelines:
  default:
    - step:
        script:
          - apt-get update -qq
          - chmod +x ./install_dependencies.sh
          - python setup.py install
          - python run_tests.py
